services:
  slim:
    build: .
    working_dir: /var/www
    ports:
      - "8888:8080"
    volumes:
      - .:/var/www
    environment:
      DB_HOST: 172.17.0.3
      DB_PORT: 3306
      DB_NAME: ciberseguridad-pIII
      DB_USER: root
      DB_PASSWORD: root
      DB_CHARSET: utf8mb4
      JWT_SECRET: juanpi